### ISSUE TITLE
Blame sidebar has white boxes.

### ISSUE THREAD

**Issue by topherfangio** [Stepsize/atom-better-git-blame#37]
_**Apologies:** Hit enter too fast and this was blank originally._

I just installed version 0.4.6 of better-git-blame into Atom 1.29.0 and am seeing white boxes over some of the commit messages. When I hover, it shows the correct thing, but it's very distracting. Is this an option that can be disabled or an actual bug?

Thanks!

#### Default View on Left / Hovered View on Right

![better-blame-white-issue](https://user-images.githubusercontent.com/54370/44430298-df33f300-a55f-11e8-9a62-0d4ae2d876b0.png)

**Comment by jaredjburgess** [comment]
The colors used a from the atom theme, I think there may be a theme where the alternating colors are less than ideal like you've seen, what UI Theme are you using? I want to try to replicate this.

Heres what it looks like on atom `1.29` with `One Dark`
<img width="251" alt="screen shot 2018-08-22 at 11 12 08" src="https://user-images.githubusercontent.com/13640069/44458020-cb8a9a00-a5fc-11e8-9af2-e3d3782b166c.png">

And just to clarify in the white boxes is there still the blame related information? Which just can't be seen due to it matching text color.

**Comment by jaredjburgess** [comment]
No problem!

Just double checking is that the [https://github.com/csutter/chester-atom-syntax](chester-atom-syntax) you are using there? I saw some variants `improved-chester-atom-syntax`, `chester-atom-2-syntax` etc...

**Comment by topherfangio** [comment]
Yes indeed!

**Comment by jaredjburgess** [comment]
With that PR above it should look like the screenshot here, whilst still retaining a visually appealing alternation on the dark themes too.

<img width="792" alt="screen shot 2018-08-22 at 19 44 59" src="https://user-images.githubusercontent.com/13640069/44483871-2398bf00-a644-11e8-83a8-b26ad3c9d57c.png">

**Comment by topherfangio** [comment]
@jaredjburgess Thanks so much man! It works great now! Very much appreciate the quick turnaround!
